### ISSUE TITLE
vf_mask label 

### ISSUE THREAD

**Issue by anslt** [robot-learning-freiburg/PanopticBEV#5]
Dear author,

I have downloaded your data for Nuscence.
I found there are 0, 1, 2 in the vf_mask, but what is the meaning of these values?

**Comment by nikhilgosala** [comment]
0 - Vertical classes in the FV image
1 - Flat classes in the FV image
2 - Unlabelled class (The semantic confidence was not high enough and we thus set it to unlabelled)

We generate these masks only for the nuScenes dataset because nuScenes does not provide FV segmentation labels for all classes of interest.
